language: csharp
solution: ReputationEssentials.sln
cache: bundler
script:
  - xbuild /p:Configuration=Debug ReputationEssentials.sln

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG

deploy:
  provider: releases
  api_key: "12c4fbd9e9dcd8e9ac0f37a786024a2d9085fa91"
  file: "/bin/debug/ReputationEssentials.sln"
  skip_cleanup: true
  on:
    tags: true
